CREATE DATABASE IF NOT EXISTS HADAM_DB;
USE HADAM_DB;

CREATE TABLE IF NOT EXISTS users (
  user_id VARCHAR(255) PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  name VARCHAR(20) NOT NULL,
  proflie VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS write_thanks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title_t VARCHAR(255) NOT NULL,
  diary_t TEXT NOT NULL,
  open_t TINYINT(1),
  date_t DATE,
  user_id VARCHAR(255),
  FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS write_regrets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title_r VARCHAR(255) NOT NULL,
  diary_r TEXT NOT NULL,
  open_r TINYINT(1),
  date_r DATE,
  user_id VARCHAR(255),
  FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS write_post (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  diary TEXT NOT NULL,
  date DATE,
  user_id VARCHAR(255),
  FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS replys (
  id INT AUTO_INCREMENT PRIMARY KEY,
  reply TEXT,
  created_at DATE,
  user_id VARCHAR(255),
  FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS uprodes (
  id VARCHAR(255) PRIMARY KEY,
  user_id VARCHAR(255),
  uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS user_activity (
  id INT AUTO_INCREMENT PRIMARY KEY,
  activity TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  user_id VARCHAR(255),
  FOREIGN KEY (user_id) REFERENCES users(user_id)
);